[tool.poetry]
name = "dragtor"
version = "0.1.0"
description = "An exploration of non-GPU RAG approaches to built an RAG-Doctor"
authors = ["Mischa <mischa@dataworkz.de>"]

[tool.poetry.dependencies]
python = "~3.11.0"
llama-cpp-python = "^0.2.87"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
