base_path: "/Users/mischa/Projects/local/dragtor/data/"
# allows to use loguru for external loggers
expose_library_logs: False
# set GPU accelerator. mps for Apple ecosystem, CUDA for NVIDIA, etc.
device: "mps"
data:
  jina_cache: "jina_reader/"
  hoopers_urls:
    - "https://www.hoopersbeta.com/library/a2-pulley-manual-for-climbers"
    # - "https://www.hoopersbeta.com/library/weight-training-and-rock-climbing"
    # - "https://www.hoopersbeta.com/library/how-to-heal-from-a-lumbrical-injury-5-simple-stages-to-recover"
    # - "https://www.hoopersbeta.com/library/flexor-tenosynovitis"
    # - "https://www.hoopersbeta.com/library/will-hangboarding-2x/day-improve-your-climbing-ultimate-revised-breakdown"
  audio_cache: "audio_transcript/"
  audio_urls:
    # - "https://cdn-media.huggingface.co/speech_samples/sample2.flac"
    - "https://cdn.simplecast.com/audio/8d0e41cc-be61-4d71-ab0d-b985db72bb92/episodes/42685a36-6381-4017-ad34-48fe1822e83e/audio/2c2a3b1c-7b39-4852-a947-6f7ea10dbf98/default_tc.mp3"
  diarize_cache: "diarize_transcript/"
chunking:
  # valid strategies: paragraph [default], jina_tokenizer, langchain
  strategy: langchain
  jina_tokenizer:
    max_chunk_length: 1000
  langchain_tokenizer:
    max_chunk_length: 1000
    chunk_overlap: 0
embeddings:
  # valid strategies: chromadb [default], jina
  strategy: jina
  jina:
    device: mps
    # max length: 8192
    max_seq_length: 512
store:
  # valid strategies: chromadb [default]
  strategy: default
  n_query: 10
  chromadb:
    path: chroma_db
    collection_name: main_collection
    # valid distances: l2, ip, cosine
    distance: cosine
reranker:
  # valid strategies: dummy [default], jina
  strategy: dummy
  n_ranked: 10
index:
  # valid strategies: basic [default], late_chunking
  strategy: default
model:
  # host: 127.0.0.1
  # port: 8080
  file_path: "/Users/mischa/Projects/local/dragtor/models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
  max_completion_tokens: 512
  kwargs:
    gpu-layers: 15
    ctx-size: 15000
prompts:
  system: >
    You are an assistant who provides advice on health care and training questions for climbers.
    You answer questions in 3 paragraphs.
  user_template: |
    Please use the following pieces of context to answer the question.
    context:

    {context}

    question:
    {question}

    answer:
server:
  backoff: 1.0
eval:
  eval_dir: "eval"
  eval_answers: "gold_answers.json"
audio:
  diarize: False
  model: "/Users/mischa/Projects/local/dragtor/models/ggml-base.en.bin"
  files: "/Users/mischa/Projects/local/dragtor/data/audio_files/"
  diarization_model: "pyannote/speaker-diarization-3.1"
  lang: "en"
  num_speakers: 2
  min_speakers: 2
  max_speakers: 2