base_path: "/Users/mischa/Projects/local/dragtor/data/"
data:
  jina_cache: "jina_reader/"
  hoopers_urls:
    - "https://www.hoopersbeta.com/library/a2-pulley-manual-for-climbers"
chunking:
  # valid strategies: jina_line [default]
  strategy: default
embeddings:
  # valid strategies: chromadb [default], mixedbread
  strategy: default
store:
  # valid strategies: chromadb [default]
  strategy: default
  chromadb:
    path: chroma_db
    # collection_name: some_name
    reset_on_load: True
model:
  file_path: "/Users/mischa/Projects/local/dragtor/models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
  max_tokens: 1024
  kwargs:
    n_gpu_layers: 15
