base_path: "/Users/mischa/Projects/local/dragtor/data/"
# allows to use loguru for external loggers
expose_library_logs: False
data:
  jina_cache: "jina_reader/"
  hoopers_urls:
    - "https://www.hoopersbeta.com/library/a2-pulley-manual-for-climbers"
    # - "https://www.hoopersbeta.com/library/weight-training-and-rock-climbing"
    # - "https://www.hoopersbeta.com/library/how-to-heal-from-a-lumbrical-injury-5-simple-stages-to-recover"
    # - "https://www.hoopersbeta.com/library/flexor-tenosynovitis"
    # - "https://www.hoopersbeta.com/library/will-hangboarding-2x/day-improve-your-climbing-ultimate-revised-breakdown"
chunking:
  # valid strategies: paragraph [default], jina_tokenizer
  strategy: default
  jina_tokenizer:
    max_chunk_length: 1000
embeddings:
  # valid strategies: chromadb [default], jina
  strategy: jina
  jina:
    device: mps
    # max length: 8192
    max_seq_length: 512
store:
  # valid strategies: chromadb [default]
  strategy: default
  n_query: 10
  chromadb:
    path: chroma_db
    collection_name: main_collection
    # valid distances: l2, ip, cosine
    distance: cosine
reranker:
  # valid strategies: dummy [default], jina
  strategy: dummy
  n_ranked: 10
index:
  # valid strategies: basic [default], late_chunking
  strategy: default
model:
  # host: 127.0.0.1
  # port: 8080
  file_path: "/Users/mischa/Projects/local/dragtor/models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
  max_completion_tokens: 512
  kwargs:
    gpu-layers: 15
    ctx-size: 15000
prompts:
  system: >
    You are an assistant who provides advice on health care and training questions for climbers.
    You answer questions in 3 paragraphs.
  user_template: |
    Please use the following pieces of context to answer the question.
    context:

    {context}

    question:
    {question}

    answer:
